# SIMULATION PARAMETERS
# number of simulations per combination of characters
n_sim: 1
# size of trees
n_tips:
    - 10
    - 50
    - 100
    - 200
    - 400
# difference between the two rates simulated
rates:
    - 1
    - 2
    - 5
    - 10
    - 100
    - 1000
# size of subclade as fraction of tree size
clade_size: 0.2
# birth death rate of trees
birth: 1.5
death: 0.5