# TREE SIMULATION PARAMETERS
# number of simulations per combination of characters
n_sim: 100
# size of trees
n_tips:
    - 10
    - 50
    - 100
    - 200
    - 400
# difference between the two rates simulated
rates:
    - 1
    - 2
    - 5
    - 10
    - 100
    - 1000
# size of subclade as fraction of tree size
clade_size: 
    - 0.2
# birth death rate of trees
birth: 1.5
death: 0.5

# prior sets with description

# Analysis selection
# not all tree combinations need to be run under the models but only this subset

sel_n_sim: 10
sel_n_tips: 
    - 10
    - 50
    - 100
    - 200
    - 400
sel_clade:
    - 0.2 
sel_rate:
    - 10
sel_prior_set:
    - 1
sel_tool:
    - "bayou"
#    - "bt"
#    - "bamm"


# MCMC parameters
n_gen: 1000000
burnin: 0.3
n_chains: 2
mcmc_write_freq: 1000
mcmc_print_freq: 1000000
mcmc_event_freq: 10

